### PR TITLE
Update dutch-diceware.wordlist.utf8.txt

### PR DESCRIPTION
**Pull request by ThisMakesSenseToMe**
The Dutch.txt word list is really bad. 

1. It contains a lot of short non-words. A lot of numbers, and symbols, and 1 and 2 letter combinations, and too short words. 
2. It goes only to words starting with the letter m
3. This results in unexpected bad Diceword passwords, and decreased entropy

Some example words that are in the bad Dutch word list: ----- begin ----- 0
1
2
3
4
5
6
7
8
9
#
##
###
?
??
???
mf
mg
mh
mi
mj
mk
ml
mm
mmm
mmmm
v
vv
vvv
vvvv
------- end -------

The new list (I suggest here ) is from: https://el-tramo.be/blog/diceware-nl (the No Composite Words list)

### CODE REVIEW

**Comment by strongbox-mark** [comment]
Hi, thanks for the suggestion... We would need to know the author for this, and if he can license it to us. We can't accept it if it's under any GPL license due to App Store regulations. Could you let us know about that.

**Comment by ThisMakesSenseToMe** [comment]
I’ll look into it. And let you know. Otherwise I’ll create a good list myself!

**Comment by strongbox-mark** [comment]
Sounds good. Instead of going via Pull Request, could you send it to support@strongboxsafe.com and we'll get it included in the next build. Cheers.

**Comment by ThisMakesSenseToMe** [comment]
I've sent you an email with the list and permission from the creator.

**Pull request closed without merging**
